#!/bin/sh

if [ "$KILL_SSH_AGENT_ON_LOGOUT" == "true" ]
then
    ssh-agent -k
fi

# clear sudo {{{
SUDO="/usr/bin/sudo"
if ! type sudo
then
  $SUDO -k
  $SUDO -K
fi
# }}}

rm -f "$HOME"/.bash_history

if [ -e /usr/bin/kdestroy ]
then
    kdestroy
fi

# custom logout {{{
for file in $HOME/.zsh.custom.logout.d
do
  [ -r "$file" ] && source "$file"
done
# }}}

clear
