#!/bin/sh

if [ "$KILL_SSH_AGENT_ON_LOGOUT" == "true" ]
then
    ssh-agent -k
fi

# clear sudo {{{
SUDO="/usr/bin/sudo"
if ! type sudo
then
  $SUDO -k
  $SUDO -K
fi
# }}}

rm -f "$HOME"/.bash_history

if [ -e /usr/bin/kdestroy ]
then
    kdestroy
fi

# custom logout {{{
CUST_LOGOUT="$HOME/.zsh.custom.logout.d"
if [[ -d $CUST_LOGOUT ]]
then
  for file in $CUST_LOGOUT/*
  do
    [ -r "$file" ] && source "$file"
  done
fi
# }}}

clear
