. $HOME/.zshenv

# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zprofile.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zprofile.pre.zsh"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zprofile.post.zsh" ]] && builtin source "$HOME/.fig/shell/zprofile.post.zsh"

BREW_BIN="/opt/homebrew/bin/brew"
if [[ -f "$BREW_BIN" ]]
then
  eval "$($BREW_BIN shellenv)"
fi
