for file in $HOME/.zsh.functions.d/*
do
  test -r "$file" && source "$file"
done

if [[ -f $HOME/.exports ]]
then
  source $HOME/.exports
fi

if [[ -f $HOME/.aliases ]]
then
  source $HOME/.aliases
fi

source $HOME/.exports-with-aliases
source $HOME/.aliases-with-exports
