# setup brew {{{
HOMEBREW_BIN="/opt/homebrew/bin/brew"
if [[ -f "$HOMEBREW_BIN" ]]
then
  eval "$($HOMEBREW_BIN shellenv)"
fi
# }}}

for file in $HOME/.zsh.functions.d/*
do
  test -r "$file" && source "$file"
done

EXPORTS_FILE="$HOME/.zsh.conf.d/exports"
if [[ -f $EXPORTS_FILE ]]
then
  source $EXPORTS_FILE
fi

ALIASES_FILE="$HOME/.zsh.conf.d/aliases"
if [[ -f $ALIASES_FILE ]]
then
  source $ALIASES_FILE
fi

source $HOME/.zsh.conf.d/exports-with-aliases
source $HOME/.zsh.conf.d/aliases-with-exports
