# rc -- zsh
# vim:fdm=marker

if [[ -z "$DISABLE_COMPLETION" ]]
then
  source $HOME/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
fi

CUST_PRE="$HOME/.zsh.custom.pre.d"
if [[ -d $CUST_PRE ]]
then
  for file in $CUST_PRE/*
  do
    test -r "$file" && source "$file"
done
fi

for file in $HOME/.zsh.pre.d/*
do
  test -r "$file" && source "$file"
done

for file in $HOME/.zsh.conf.d/*
do
  test -r "$file" && source "$file"
done

command -v mesg &> /dev/null && mesg n

autoload zcalc

source $HOME/.zsh/k/k.sh
source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /usr/local/bin/aws_zsh_completer.sh ] && source /usr/local/bin/aws_zsh_completer.sh

source_os_dotfiles zshrc

if [[ "$HOST_IP" == "" ]]
then
  echo_color red "No IP address(es) detected"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

test $commands[kubectl] && source <(kubectl completion zsh)

for file in $HOME/.zsh.post.d/*
do
  test -r "$file" && source "$file"
done

for file in $HOME/.zsh.custom.d/*
do
  test -r "$file" && source "$file"
done

CUST_POST="$HOME/.zsh.custom.post.d"
if [[ -d $CUST_POST ]]
then
  for file in $CUST_POST/*
  do
    test -r "$file" && source "$file"
  done
fi

cd ~
