# rc -- zsh
# vim:fdm=marker

for file in $HOME/.zsh.pre.d/*
do
  test -r "$file" && source "$file"
done

for file in $HOME/.zsh.d/*
do
  test -r "$file" && source "$file"
done

type mesg > /dev/null
if [ $? -eq 0 ]
then
    mesg n
fi

rationalise-dot() {
    if [[ "$LBUFFER" == *.. ]]
    then
        LBUFFER+=/..
    else
        LBUFFER+=.
    fi
}
zle -N rationalise-dot
bindkey . rationalise-dot

source $HOME/.zsh/k/k.sh

autoload zcalc

source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /usr/local/bin/aws_zsh_completer.sh ] && source /usr/local/bin/aws_zsh_completer.sh

source_os_dotfiles zshrc

if [[ "$HOST_IP" == "" ]]
then
    echo_color red "No IP address(es) detected"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

test $commands[kubectl] && source <(kubectl completion zsh)

cd ~

for file in $HOME/.zsh.post.d/*
do
  test -r "$file" && source "$file"
done

for file in $HOME/.zsh.custom.d/*
do
  test -r "$file" && source "$file"
done
