local opt = vim.opt

opt.encoding = "utf-8"
opt.expandtab = true
opt.nu = true
opt.errorbells = true
opt.wrap = true
opt.smartcase = true
opt.swapfile = true
opt.backup = true
opt.incsearch = true
opt.autoindent = true
opt.hlsearch = false
opt.completeopt = "menu,menuone,noselect"
opt.sw = 2
opt.ts = 2
opt.sts = 2
opt.fillchars = {eob = " "}
opt.cmdheight = 0
opt.ignorecase = true
opt.undodir = "/tmp/nvim-undo/"
opt.ruler = true
opt.laststatus = 0
opt.signcolumn = "yes:1"
opt.backupdir = "/tmp/nvim-backup/"
opt.cmdheight = 2
opt.laststatus = 2
opt.winwidth = 90
opt.textwidth = 99
opt.smartindent = true
opt.cursorline = true
