#!/bin/sh

if [ "$KILL_SSH_AGENT_ON_LOGOUT" == "true" ]
then
    ssh-agent -k
fi

SUDO="/usr/bin/sudo"
if ! type sudo
then
  $SUDO -k
  $SUDO -K
fi

rm -f "$HOME"/.bash_history

if [ -e /usr/bin/kdestroy ]
then
    kdestroy
fi

if [ -f "$HOME"/.logout-custom ]
then
  source "$HOME"/.logout-custom
fi

clear
