#!/bin/sh

if [ "x$KILL_SSH_AGENT_ON_LOGOUT" == "xtrue" ]
then
    ssh-agent -k
fi

if ! type sudo
then
  echo yes | sudo -k
  echo yes | sudo -K
fi

rm -f $HOME/.bash_history

if [ -e /usr/bin/kdestroy ]
then
    kdestroy
fi

if [ -f $HOME/.logout-custom ]
then
  source $HOME/.logout-custom
fi

clear
