# conf.d/aliases_git.fish
# mirrors: dotfiles/zsh.conf.d/aliases-git

abbr --add ga 'git a'
abbr --add 'ga.' 'git aa'
abbr --add gaa 'git aa'
abbr --add gb 'git b'
abbr --add gba 'while read l; cd $l; git branch | grep --invert-match main; end'
abbr --add gbam 'while read l; cd $l; git branch | grep --invert-match master; end'
abbr --add gbd 'gco main; gl; gf --prune; git remote prune origin; git branch --delete'
abbr --add gbdm 'gco master; gl; gf --prune; git remote prune origin; git branch --delete'
abbr --add gbm gbsum
abbr --add gbsu 'git bsu'
abbr --add gbsum 'git bsum'
abbr --add gbsums 'git bsums'
abbr --add gc 'git c'
abbr --add gca 'git ca'
abbr --add gcaa 'git caa'
abbr --add gcd 'git clean -d --force'
abbr --add gcf 'git clean --force'
abbr --add 'gco.' 'git checkout -- .'
abbr --add gco 'git checkout'
abbr --add gcob 'git checkout main; git pull; git checkout main -b'
abbr --add gcobm 'git checkout master -b'
abbr --add gcp 'git cherry-pick'
abbr --add gcpc 'git cherry-pick --continue'
abbr --add gd 'git diff'
abbr --add gdi 'git di'
abbr --add gds 'git ds'
abbr --add gf 'git f'
abbr --add gfrm 'git f && git rbms && git p; git pf'
abbr --add gi 'git info'
abbr --add gitall 'ls -d */ | xargs -P10 -I{} git -C {} '
abbr --add gl 'git pull'
abbr --add glg 'git log'
abbr --add 'glo.' 'git log .'
abbr --add glo 'git log'
abbr --add 'glop.' 'git log --patch .'
abbr --add glop 'git log --patch'
abbr --add glot 'git log --tags'
abbr --add glu 'git pull upstream'
abbr --add glum 'git pull upstream main'
abbr --add glums 'git pull upstream master'
abbr --add glup 'glum && gp'
abbr --add glups 'glums && gp'
abbr --add gp 'git p'
abbr --add gpf 'git pf'
abbr --add gpfn 'git pf --no-verify'
abbr --add gr 'git restore'
abbr --add gra 'git remote add'
abbr --add grao 'git remote add origin'
abbr --add grau 'git remote add upstream'
abbr --add grb 'git rebase --interactive'
abbr --add grbm 'git rebase --interactive origin/main'
abbr --add grbms 'git rbms'
abbr --add grbs 'git rebase --skip'
abbr --add grc 'git rebase --continue'
abbr --add grp groups
abbr --add grs 'git restore --staged'
abbr --add 'gst.' 'git status .'
abbr --add gst 'git status'
abbr --add rgh 'rm --recursive --force --verbose .git/hooks && git init'
abbr --add gll fzf_git_log
