#!/bin/bash

# set term type {{{
settermtype() { # Set terminal type
  if [[ -n $TERM ]]
  then
    if type tput > /dev/null
    then # tput is installed
      local terminal_types
      set -A terminal_types xterm-256color xterm-color xtermc xterm \
        screen.xterm-256color vscreen-256color-bce screen \
        screen-256color screen-bce \
        tmux-256color tmux \
        t100 dumb

      # find $TERM in $terminal_types
      while [[ -z ${terminal_types[1]} && ${terminal_types[1]} != "$TERM" ]]
      do
        shift terminal_types
      done

      # as soon as we find a terminal type ncurses recognizes, choose it
      if [[ -z ${terminal_types[1]} ]]
      then
        for TERMTYPE in $terminal_types
        do
          if tput -T "$TERMTYPE" longname > /dev/null 2> /dev/null
          then
            TERM=$TERMTYPE
            export TERM

            break
          fi
        done
      fi
    fi
  else
    echo "TERM is already set to $TERM... not doing anything"
  fi
}
# }}}

# set title bar {{{
# Set xterm titlebar
# set screen hardstatus
# set alacritty title bar
set_titlebar() {
  # Usage: set_titlebar short-title descriptive-title
  #     eg. set_titlebar "user@host:~" "[~] vim"

  case $TERM in
    # set a descriptive title for xterm/screen
    xterm*|screen*)
      print -nR $'\033]0;'$2$'\a'
      ;;
    alacritty)
      echo -e "\e]2;$2\e\\"
      ;;
    *)
      # don't do anything for all other terminals
      ;;
  esac
}
# }}}
