#!/bin/bash

usage() {
  cat <<EOF
Syntax: $(basename "$0") [args] filename
  -v - verbose
EOF
}

while getopts "vhf:" opt
do
  case $opt in
    f)
      FILE="$OPTARG"
      ;;
    v)
      VERBOSE="true"
      ;;
    h|?)
      usage

      exit 0
      ;;
    *)
      usage

      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

if [[ -z "$FILE" ]]
then
  usage

  exit 22
fi

if [[ "$VERBOSE" == "true" ]]
then
  set -x
fi

log() {
  [[ "$VERBOSE" == "true" ]] && $*
}

TEMP_PUTTY="$(mktemp)"
TEMP="$(mktemp)"
OPENSSL="openssl rsa"
MD5="openssl md5 -c"
KEYGEN="ssh-keygen -f $TEMP"

puttygen $FILE -O private-openssh -o $TEMP_PUTTY
log cat $TEMP_PUTTY
$OPENSSL -in $TEMP_PUTTY -out "$TEMP"

echo "ec2 priv"
ssh-keygen -f "$TEMP" -e -m PKCS8 | openssl pkey -pubin -outform DER | $MD5
echo ""
echo "ec2 pub"
ssh-keygen -f "$FILE".pub -e -m PKCS8 | openssl pkey -pubin -outform DER | $MD5

echo "==============================================================================="

echo "openssl"
$OPENSSL -in "$TEMP" | $MD5

echo "==============================================================================="

echo "ssh"
$KEYGEN -l

echo "==============================================================================="

echo "ssh -> openssl"
$KEYGEN -e -m PEM | $OPENSSL -RSAPublicKey_in -outform DER | $MD5
