#!/bin/sh

set -x

if [[ $(uname) == "Darwin" ]]
then
  CHMOD="chmod -v"
else
  CHMOD="chmod --verbose"
fi

FILE_PERM="600"
EXEC_PERM="700"

$CHMOD $FILE_PERM *

$CHMOD $EXEC_PERM . check-fingerprints fix-permissions ssh-key
