#!/bin/bash

usage() {
  echo "$(basename $0) keyname [-g]"
  echo "    -g generate new key"
}

while getopts "hg" opt; do
    case "$opt" in
      h)
        usage
        exit 0
        ;;
      g)
        GENERATE="true"
        ;;
      *)
        usage
        exit 1
        ;;
    esac
done
shift $((OPTIND - 1))

if [[ "$#" -lt 1 ]]
then
  echo "keyname must be specified"
  echo ""

  usage
  exit 1
fi
KEY="$1"
shift

set -x

KEYGEN="ssh-keygen -f $KEY -t ed25519"

if [[ "$GENERATE" == "true" ]]
then
  $KEYGEN
else
  vim $KEY

  chmod 600 $KEY

  $KEYGEN -p
fi

./fix-permissions

$KEYGEN -y | tee "$KEY.pub"
